### ISSUE TITLE
Upcoming Vid2Vid closed mouth

### ISSUE THREAD

**Issue by Inferencer** [KwaiVGI/LivePortrait#114]
So when using vid2img it's best if the mouth is the same openness which is normally resolved rather easily by making sure both mouths are closed first by using your re-targeting if needed for the source image and then also ensuring the first driving frame is closed.

Would vid2vid require a closed mouth on all source video frames or just the first frame 
and if the latter when we move over to vid2vid we may be limited on the source vid length if we are cutting to ensure first frame contains a closed mouth, what would be the best solution would it be suitable to: 
Duplicate the first frame > 
Re-target it so the mouth is closed >
Move that re-targeted frame to the start of the video sequence >
Animate >
Remove first frame from the result video.

**Comment by AlonDan** [comment]
First of all, great points and suggestions @Inferencer I'm also curious about it 👍

It can help with the start-point and then "re-shape" via the re-target feature.

---

Via my random tests, I did found out something interesting! 🤔

If the SOURCE is smiling with showing teeth, and the Driving will be similar it can only help as a "start point" without making the smile more extreme (since you start with a smile instead of a "neutral expression face" (means no smile, mouth closed, looking towards the camera).

One conclusion is if you use the SOURCE and DRIVING with SIMILAR expressions you will get a nice result, at least based on some of my random experiments so far. (I know they are not recommend that, but using a NEUTRAL expression face, but I had to test this).

Another VERY USEFUL thing I found out:
If the SOURCE is a SMILE showing TEETH, the RESULT will respect and KEEP the SAME TEETH STRUCTURE of the source on the FINAL RESULT VIDEO!

As you may know, TEETH can defiantly CHANGE the person's face, that means it will look MORE SIMILAR to the ORIGINAL SOURCE if you SHOW their TEETH, test it for yourself and see what I mean.

Again, it's not recommended based on the way it should work with NEUTRAL expression face, but it DOES make the face more similar to the original one at the end.

**Comment by Inferencer** [comment]
Thanks for the confirmation on teeth, I did wonder about that, perhaps at a later date if confirmed my above comment structure is correct for a source video on vid2vid then perhaps a similar approach can be achieved with the driving video on image portrait so that the first frame of the driving vid is re-targeted to match the source image to retain source image fidelity rather than re-targeting the source image.

**Comment by AlonDan** [comment]
I really hope that we will have the option to choose a "REFERENCE" as the "start-point" on both Source and Driving video, think of it as a keyframe.
That way we can keyframe what will be the MOST-SIMILAR pose / emotion of the face on both manually and when start RENDERING it will have a START POINT as reference to make things more accurate.

It's just an idea, but I hope that the developers will consider this.

**Comment by Inferencer** [comment]
oh that clever so you mean render backwards and forwards rather than start to finish that would be smart
![6f47b135-1dd7-498d-9473-3afaeeffbc5f_text](https://github.com/user-attachments/assets/a31fb9d1-8253-46aa-9972-91d2091395c8)

**Comment by AlonDan** [comment]
@Inferencer can you please explain step-by-step how to run this?
I guess it's not working via the Gradio App yet, but it seems like you successfully got some nice  Vid2Vid results via the `inference.py` (not sure)

Since there is no official Vid2Vid yet, I would like to test it if possible, similar to your example: #116 

Since I'm no programmer, sorry for the confusion:
Do I need to download some files / overwrite? in order to test this?

Thanks ahead 🙏

**Comment by Inferencer** [comment]
> @Inferencer can you please explain step-by-step how to run this? I guess it's not working via the Gradio App yet, but it seems like you successfully got some nice Vid2Vid results via the `inference.py` (not sure)
> 
> Since there is no official Vid2Vid yet, I would like to test it if possible, similar to your example: #116
> 
> Since I'm no programmer, sorry for the confusion: Do I need to download some files / overwrite? in order to test this?
> 
> Thanks ahead 🙏

That's not mine that another dev, you can download his code from his [fork](https://github.com/ymuhong/LivePortrait-Advanced/tree/main)

**Comment by Inferencer** [comment]
https://github.com/user-attachments/assets/6a2e9e05-e12e-4225-8788-dc4934798534

I have confirmed re-targeting the first frame of the driving vid works well

**Comment by ymuhong** [comment]
> @Inferencer can you please explain step-by-step how to run this? I guess it's not working via the Gradio App yet, but it seems like you successfully got some nice Vid2Vid results via the `inference.py` (not sure)
> 
> Since there is no official Vid2Vid yet, I would like to test it if possible, similar to your example: #116
> 
> Since I'm no programmer, sorry for the confusion: Do I need to download some files / overwrite? in order to test this?
> 
> Thanks ahead 🙏

Yes, I mainly updated `inference.py`. I didn't check to see if changes work for the gradio app. I'll go ahead and test it out on my end and update my [fork](https://github.com/ymuhong/LivePortrait-Advanced/tree/main) once I have it working

**Comment by AlonDan** [comment]
It will be great to test it via the Gradio API, I hope you can make it because we have no idea when the official release to Vid2Vid will be released in the official version. 

I hope that the developers will release it soon of course because the official Vid2Vid examples are VERY impressive 👍

**Comment by AlonDan** [comment]
I'm trying your fork @ymuhong via the inference (I just replaced the .jpg with .mp4)
But I always get a full BOXED background moving with the head.

Is there a command I need to add to the line to get rid of the BOXED background?

**Comment by ymuhong** [comment]
> It will be great to test it via the Gradio API, I hope you can make it because we have no idea when the official release to Vid2Vid will be released in the official version.
> 
> I hope that the developers will release it soon of course because the official Vid2Vid examples are VERY impressive 👍

I hope they release it too. Curious to see how they've implemented Vid2vid in theirs.
I got the Gradio app working btw, try it out and let me know

**Comment by ymuhong** [comment]
> I'm trying your fork @ymuhong via the inference (I just replaced the .jpg with .mp4) But I always get a full BOXED background moving with the head.
> 
> Is there a command I need to add to the line to get rid of the BOXED background?

If you're using inference.py, you need to add the flag ` --no-flag-do-crop`
You also need to uncheck it  **do crop (source)** in the advanced dropdown if you're using Gradio

**Comment by AlonDan** [comment]
Thanks for applying it to the Gradio App, I just tried to test it but I get errors:

```
cv2.error: OpenCV(4.10.0) :-1: error: (-5:Bad argument) in function 'resize'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'
```

In case it helps: the original project doesn't give me any errors.

I've tried as you recommended with the "**do croup (source)**" unchecked 👍

If you want to test the same exact file I tried, you can download the [reference HERE.](https://pixabay.com/videos/girl-heart-gesture-symbol-asian-129421/)

I used the TINY resolution, since the face is already pretty close to the camera also I don't have much VRAM (only 4GB) but I never had out of memory so far with any of my other tests.

![chrome_2024-07-13_16-45-26](https://github.com/user-attachments/assets/3dddfbe2-81dd-49d2-9a2a-a998324be4ef)

I can't get any result because I get an error (I also tried other videos), same error appears.
But I wonder if I will get the same BOXED Background moving as I did with the last inference version I tested, so if you fixed it please let me know and I'll try again in Gradio App.


Also please feel free to share YOUR test so we can compare, maybe something is wrong on my side.

**Comment by AlonDan** [comment]
I just tested it also with the inference, I get the same error as mentioned above so I can't really get any result to give feedback yet.

**Comment by ymuhong** [comment]
> I just tested it also with the inference, I get the same error as mentioned above so I can't really get any result to give feedback yet.

Sorry about that... my recent merge with the the original repo screwed up one of my previous fixes. 😩
It should be working now.

**Comment by AlonDan** [comment]
I just tried the latest version but now I get this error when trying to process:

`RuntimeError: FIND was unable to find an engine to execute this computation after trying 10 plans.`

**Comment by AlonDan** [comment]
So I guess it does work on some files but in some not, can't tell what exactly cause the error I mentioned above.
The above example VIDEO REFERENCE that I shared it's link CAUSE that error I shared above.
Some other videos did the same, some not.

---

But even if I success processing some of the source videos, one thing is for sure:
I still get that "BOXED FRAME" of the mask as mentioned before.
Do I need to Enable/Disable anything else in order to get rid of that for smooth stitching result?

If I uncheck "do crop (source)" as you suggested it will make the whole video into a 1:1 boxed video, if I leave it checked (default) it will make the BOXED FRAME effect...

What am I missing?

---

Here is one example:

🚫 do crop (source) = **UNCHECK**
https://github.com/user-attachments/assets/91cfa61a-9fdf-4cd2-9619-d0fd7653f23c

✅ do crop (source) = **CHECK** (default)
https://github.com/user-attachments/assets/f4425aa4-6938-41fb-a785-250e4aaa2966

📎 Source file in case you want to do the exact same test:
https://github.com/user-attachments/assets/1a0bbabd-e6d1-476b-b112-4ca0e9457bf6

![chrome_2024-07-13_22-51-04](https://github.com/user-attachments/assets/74c0cc69-3476-4d05-919a-42feceec4b2d)

**Comment by ymuhong** [comment]
This behavior is a direct result of unchecking **do crop (source)** or using the `--no-flag-do-crop` flag. It also happens in the original repo when you uncheck it and use it with an image that doesn't have a 1:1 ratio in the source.

I'm working on a fix but in the meantime, your input source video should be cropped with a 1:1 ratio.

**Comment by Inferencer** [comment]
Solved by following my own workflow at the start in addition to adding extra footage for extra ref frames at the end

**Comment by mhwu2017** [comment]
> image-3--Untitled44.1.mp4 
> I have confirmed re-targeting the first frame of the driving vid works well

Could you tell me how to retarget the first frame? Use LivePortrait itself or another algorithm?

**Comment by rohit7044** [comment]
> First of all, great points and suggestions [@Inferencer](https://github.com/Inferencer) I'm also curious about it 👍
> 
> It can help with the start-point and then "re-shape" via the re-target feature.
> 
> Via my random tests, I did found out something interesting! 🤔
> 
> If the SOURCE is smiling with showing teeth, and the Driving will be similar it can only help as a "start point" without making the smile more extreme (since you start with a smile instead of a "neutral expression face" (means no smile, mouth closed, looking towards the camera).
> 
> One conclusion is if you use the SOURCE and DRIVING with SIMILAR expressions you will get a nice result, at least based on some of my random experiments so far. (I know they are not recommend that, but using a NEUTRAL expression face, but I had to test this).
> 
> Another VERY USEFUL thing I found out: If the SOURCE is a SMILE showing TEETH, the RESULT will respect and KEEP the SAME TEETH STRUCTURE of the source on the FINAL RESULT VIDEO!
> 
> As you may know, TEETH can defiantly CHANGE the person's face, that means it will look MORE SIMILAR to the ORIGINAL SOURCE if you SHOW their TEETH, test it for yourself and see what I mean.
> 
> If you DON'T use "showing teeth" as a start-point (first frame) it will CREATE some random teeth that are NOT similar to the original source face!
> 
> Again, it's not recommended based on the way it should work with NEUTRAL expression face, but it DOES make the face more similar to the original one at the end.

I just did an experiment and found out that if the source and driving video has no teeth, the model still generates teeth. Any solution for that?
